### ISSUE TITLE
Warrior - Protection <-> Fury

### ISSUE THREAD

**Issue by shabazza** [TekNoLogic/Crossdresser#1]
Hello,

i got some small problem. Im a warrior and have Protection as primary specc and Fury as secondary. When i switch from Protection to Fury everything is fine. The equipment changed. When i try to switch back to Protection Crossdresser cant equip my weapon and shield. I think the problem is, that my warrior has still 2 x 2handweapon equiped without the talent Titangrip. I have to manually unequip the twohand weaopn on the offhand. Is this a problem that blizz might fix ? Or is there any chance Crossdresser can handle this ?

regards, Sha

**Comment by tekkub** [comment]
if you turn off CD and load the equipment sets manually do they work, or do you have to manually load the weapon/shield there too?

**Comment by shabazza** [comment]
unfortunately its the same behavior without cd. :( no way to unequip the weapon in offhand with a script or lua, right ? one solution is to equip the protstuff bevor i specc to protection. but this is not so great....

regards, sha

**Comment by tekkub** [comment]
If it's a bug in the equip manager, it's not something I'm going to fix.  Yes, you can equip/unequip items via lua.  This must be a weird special case for warriors, my pally swaps just fine between a 2H and 1H/shield.

**Comment by shabazza** [comment]
i have questioned this in the gamemaster forum from blizz. its a known problem an would be fixed in a future patch. than i have to wait. :)

thanks for your effort.

regards, sha
