### ISSUE TITLE
GetActiveTalentGroup() has been replaced by GetActiveSpecGroup()

### ISSUE THREAD

**Issue by brotherhobbes** [TekNoLogic/Crossdresser#10]
As of patch 5.0.4 the function GetActiveTalentGroup() has been replaced by GetActiveSpecGroup().

Line numbers 44, 53, and 55 need to be changed from GetActiveTalentGroup() to GetActiveSpecGroup().

Occasionally still get error message "You can't do that right now" and gear is not swapped, but this is not a new issue.

**Comment by tekkub** [comment]
I have a fix pending.
