### ISSUE TITLE
Character window

### ISSUE THREAD

**Issue by liddo** [TekNoLogic/Crossdresser#3]
Crossdresser doesn't work when you switch talents with the Character info window open. Gives the "you can't do this right now" error. Once you get this error and you close the Character window, the error still persists until you unequip something (I think...).

Like with the other issue, I don't know if its Blizzard's issue or CD. Surely can be avoided though by getting CD to close the character window before equipping?

**Comment by liddo** [comment]
OK After playing around some more, it seems random. I don't know what's causing it anymore :/. Tried going from DW to 2H to DW, and 2H to 2H and DW to DW. All seem to be getting errors but works fine when I do it manually. Unlike the warrior, I don't have any talents that would restrict my weapons (DK).

**Comment by liddo** [comment]
Would it be latency issue? I tried to replicate this issue manually. Disabled CD. Spamming the equip button while switch specs, gets you the "you can't do this right now" error until it finishes the switch talent spell cast and the action bars reappear. Needs delay?

In Australia where 400ms+ pings are average.

**Comment by tekkub** [comment]
I've never run into issue, but there have been a number of issues with weapons and the EM.  What exactly do you mean by "when the action bars reappear"?  Everything seems to happen at the same time from what I can tell.

**Comment by liddo** [comment]
You know when you switch talents.. using the default action bar with the gryphons, theres a slight sliding out and in animotion with both the mainbars and the side bars.

**Comment by tekkub** [comment]
I don't use the default bars, that animation is just fluff.  The switch in the client is actually instant.

**Comment by benomine** [comment]
Hey there, i'm experiencing the same issue reported above but only in zones where there's lot of lags (Dalalag for example). It seems it just happens with a big latency and never with normal zones.
