### ISSUE TITLE
sometimes fails to equip set

### ISSUE THREAD

**Issue by Sano** [TekNoLogic/Crossdresser#4]
On occasion, I will switch specs and get the error message "Can't perform that action right now" and my equipment set has not changed.  I suspect there needs to be a short pause before attempting to equip the set after the spec switch.

**Comment by tekkub** [comment]
I have never been able to reproduce this.

**Comment by Sano** [comment]
Changing the EquipmentManager_EquipSet call to UseEquipmentSet solved the issue for me.  For reference, here is the EquipmentManager function as defined by Blizzard:

function EquipmentManager_EquipSet (name)
    if ( EquipmentSetContainsLockedItems(name) or UnitCastingInfo("player") ) then
        UIErrorsFrame:AddMessage(ERR_CLIENT_LOCKED_OUT, 1.0, 0.1, 0.1, 1.0);
        return;
    end

```
UseEquipmentSet(name);
```

end

Fork here:

http://github.com/Sano/Crossdresser/tree/

**Comment by ghost** [comment]
I get this every once in a while aswell

**Comment by Zidomo** [comment]
Same. In WoW 3.3.5 it happens here about 95% of the time on 3 different characters. This issue should still be open as Crossdresser 3.3.0.2-Release has this problem

Sano's change above solves the issue, though. Change line 65 of Crossdresser.lua from EquipmentManager_EquipSet(name) to UseEquipmentSet(name). No further problems so far.

**Comment by ghost** [comment]
The issue is that the event that is used is fired a bit too early, and the server thinks you are still casting.
Replacing PLAYER_TALENT_UPDATE with ACTIVE_TALENT_GROUP_CHANGED fixes this.
[Spequip](http://github.com/p3lim/Spequip) uses this event, and there still havent been any issue registered.

**Comment by Zidomo** [comment]
Crossdresser build fa13f2af582e23865714 still doesn't fix this problem (changed to use above event from p3lim).

Switching specs and then getting the "You can't do that right now" error doesn't happen quite as much as it did with v3.3.0.2-Release, but it still happens the majority of the time here.

The only fix/workaround to this issue I've verified to work 100% of the time is the "Change line 65 of Crossdresser.lua from EquipmentManager_EquipSet(name) to UseEquipmentSet(name)" posted above.
